### ISSUE TITLE
Levantar a v0.1 do site da mentoriaIaC

### ISSUE THREAD

**Issue by afonsoaugusto** [mentoriaiac/mentoriaiac.github.io#1]
O objetivo desta Issue é levantar a primeira versão do site da mentoriaIaC utilizando Github Pages.

Frameworks possíveis inicialmente:
- [gohugo.io](https://gohugo.io/)
  - [hugo on github pages](https://gohugo.io/hosting-and-deployment/hosting-on-github/)
- [jekyll](https://jekyllrb.com/)
  - [jekyll on github pages](https://docs.github.com/pt/pages/setting-up-a-github-pages-site-with-jekyll)

Primeira reunião para o assunto será no dia 16/06/2021 às 19:30

**Comment by afonsoaugusto** [comment]
Boa noite pessoal,
Hoje eu não estou muito bem para a reunião e em conversa com o
@AdennTumba e @marcio_machado concluimos que seria interessante antes de puxarmos o assunto do site para a mentoria, em termos um tema a ser adotado no site.

Como base de tema, temos o https://themes.gohugo.io/ e lá podemos escolher.

Acho que seria interessante para organizar essa escolha, utilizarmos a issue https://github.com/mentoriaiac/mentoriaiac/issues/1, 
pq assim podemos sugerir o tema e lá podemos votar.

**Comment by marcelomansur** [comment]
Eu posso ajudar a subir o tema escolhido no Github pages, fiz um recentemente pro meu repositório pessoal. Mas basicamente um [Actions](https://gohugo.io/hosting-and-deployment/hosting-on-github/#build-hugo-with-github-action) resolve o problema :)

**Comment by marcelomansur** [comment]
Pessoal, tem um tema interessante aqui, bem minimalista:
https://themes.gohugo.io/hugo-theme-hello-friend-ng/

Tá bem atualizado em relação aos commits e as issues corrigidas. Valeu🍺

**Comment by zokaibr** [comment]
@afonsoaugusto como ficou o site da Mentoria IAC? Eu manjo um pouco de Jekyll, posso dar um help pra subir um site com ele. 

Achei agora pouco uma lista interessante de temas do Jekyll:
https://jamstackthemes.dev/ssg/jekyll/
