### ISSUE TITLE
Modificar nome do repositório de mentoriaiac para mentoriaiac.github.io

### ISSUE THREAD

**Issue by afonsoaugusto** [mentoriaiac/mentoriaiac.github.io#2]
Issue para levantar o tema se é relevante modificar o nome do repositório.
Eu pergunto isso pq no github.pages se o nome ficar mentoriaiac.github.io a home do pages vira esse repositório.

**Comment by ya-kimura** [comment]
Olá, Afonso. Acho pertinente seu questionamento, não vejo impedimentos para isso. Mas fiquei com dúvidas sobre a issue #1, vai seguir naquela ideia ainda?

**Comment by afonsoaugusto** [comment]
> Olá, Afonso. Acho pertinente seu questionamento, não vejo impedimentos para isso. Mas fiquei com dúvidas sobre a issue #1, vai seguir naquela ideia ainda?

Sim, podemos segui na linha da issue #1.
E o ideal é isso msm, sendo este repositório ser a home e os demais se tiverem um conteúdo web, ser uma composição do site.

O que eu penso @ya-kimura,
O repositório mentoriaiac.github.io ser a Home com paginas auxiliares e tals.
Mas o repositório, por exemplo, https://github.com/mentoriaiac/glossario ter uma pagina e a url fica desta forma: mentoriaiac.com.br/glossario
Ou o repo https://github.com/mentoriaiac/Makefiles ter um conteudo web e a url fica assim: mentoriaiac.com.br/Makefiles
